Some gradual updates

diff --git a/zsh/functions/aws-ssh b/zsh/functions/aws-ssh
--- a/zsh/functions/aws-ssh
+++ b/zsh/functions/aws-ssh
@@ -1,34 +1,20 @@
 # will attempt to login to the IP address of the aws instance id
 
 aws-ssh() {
-  local KNIFE_PATH='/opt/chef-workstation/bin/knife'
   INSTANCE_ID="$1"
   if [[ -z $INSTANCE_ID ]]; then
-    echo 'Need to pass in an instance id USAGE: `aws-ssh <instance-id>`'
+    echo 'Need to pass in an instance id USAGE: `aws-ssh <instance-id>`' >&2
     return 1
   fi
 
-  SEARCH_STRING="ec2_instance_id:$INSTANCE_ID"
-  RESULTS_RESPONSE=$($KNIFE_PATH search $SEARCH_STRING -F json -a ipaddress)
-  RESULTS=$(echo "$RESULTS_RESPONSE" | jq -r '.results')
-
-  if [ "$RESULTS" -lt "1" ]; then
-    echo "No Results Found for $INSTANCE_ID"
-    return 1
-  fi
-
-  if [ "$RESULTS" -gt "1" ]; then
-    echo "More than one result found for $INSTANCE_ID"
-  fi
-
-  IP_ADDRESS="$(echo "$RESULTS_RESPONSE" | jq -r '.rows[0][].ipaddress')"
+  IP_ADDRESS="$(aws-resolve-ip $INSTANCE_ID)"
 
   if [[ -z $IP_ADDRESS ]]; then
-    echo "IP Address not found for $INSTANCE_ID"
+    echo "IP Address not found for $INSTANCE_ID" >&2
     return 1
   fi
 
-  echo "Attempting to login to $INSTANCE_ID via $IP_ADDRESS"
+  echo "Attempting to login to $INSTANCE_ID via $IP_ADDRESS" >&2
 
   ssh $IP_ADDRESS
 }
